Fix tests
yiisoft/yii-gii pull request #51
Opened 2022-09-21 11:05 UTC by xepozz

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️

2022-09-21 11:27 UTC, arogachev commented on src/Generator/AbstractGenerator.php
> +        $results = $this->validator->validate($this, $this->rules());
```suggestion
        $result = $this->validator->validate($this, $this->rules());
```

2022-09-21 11:28 UTC, arogachev commented on src/Generator/AbstractGenerator.php
>          return $results;
Need to return errors.

2022-09-21 11:30 UTC, arogachev requested changes
:+1:

2022-09-21 11:32 UTC, xepozz commented on src/Generator/AbstractGenerator.php
>          return $results;
The result of the validation is enough.

2022-09-22 16:15 UTC, arogachev commented on src/Generator/Controller/default/controller.php
> +$classModifiers = [];
```suggestion
$classDefinitionParts = [];
```

2022-09-22 16:19 UTC, arogachev approved these changes

2022-09-22 18:24 UTC, merged