update links (http=>https)
yiisoft/yii-gii pull request #67
Opened 2022-12-16 00:26 UTC by Arhell

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | -

2022-12-16 07:37 UTC, vjik requested changes

2022-12-16 07:37 UTC, vjik commented on docs/guide-ja/basic-usage.md
> +PHPStorm の [クリップボードと比較](https://www.jetbrains.com/phpstorm/webhelp/comparing-files.html) のような IDE の機能を使うと良いでしょう。
```suggestion
PHPStorm の [クリップボードと比較](https://www.jetbrains.com/help/phpstorm/comparing-files-and-folders.html) のような IDE の機能を使うと良いでしょう。
```

2022-12-16 07:37 UTC, vjik commented on docs/guide-ja/basic-usage.md
> +[Aptana Studio](https://www.aptana.com/products/studio3/download) や [Eclipse](https://www.eclipse.org/pdt/) ベースのエディタも [AnyEdit tools plugin](https://andrei.gmxhome.de/anyedit/) を使って [クリップボードと比較](http
```suggestion
[Aptana Studio](http://www.aptana.com/) や [Eclipse](https://www.eclipse.org/pdt/) ベースのエディタも [AnyEdit tools plugin](https://andrei.gmxhome.de/anyedit/) を使って [クリップボードと比較](https://andrei.gmxhome.de/anyedit/examples.html) をすることが出来ます。
```

2022-12-16 07:37 UTC, vjik commented on docs/guide-ja/basic-usage.md
> +[Aptana Studio](https://www.aptana.com/products/studio3/download) や [Eclipse](https://www.eclipse.org/pdt/) ベースのエディタも [AnyEdit tools plugin](https://andrei.gmxhome.de/anyedit/) を使って [クリップボードと比較](http
https://andrei.gmxhome.de/ — broken link

2022-12-17 06:16 UTC, Arhell commented on docs/guide-ja/basic-usage.md
> +PHPStorm の [クリップボードと比較](https://www.jetbrains.com/phpstorm/webhelp/comparing-files.html) のような IDE の機能を使うと良いでしょう。
Done thanks

2022-12-17 06:16 UTC, Arhell commented on docs/guide-ja/basic-usage.md
> +[Aptana Studio](https://www.aptana.com/products/studio3/download) や [Eclipse](https://www.eclipse.org/pdt/) ベースのエディタも [AnyEdit tools plugin](https://andrei.gmxhome.de/anyedit/) を使って [クリップボードと比較](http
Done thanks

2022-12-17 07:20 UTC, vjik approved these changes

2022-12-17 07:20 UTC, merged